var converter = require('postcss-to-js');
var loaderUtils = require('loader-utils');
var babel = require('babel-core');

var toStyled = require('./generators/styled-components');

function isStyledChosen(config) {
  return config.use == 'styled-components' || config.styledComponents;
}

function isEmoticonChosen(config) {
  return config.use == 'emoticon' || config.emoticon;
}

function isJSS(config) {
  return config.use == 'jss' || config.jss;
}

function babelify(result, mode) {
  return babel.transform(result, {
    babelrc: true,
    "plugins": [
      "transform-es2015-modules-commonjs",
      "transform-es2015-template-literals"
    ]
  }).code;
}

module.exports = function (source) {
  this.cacheable(true);
  var callback = this.async();

  var config = loaderUtils.getOptions(this) || {
      use: 'styled-components'
    };

  var complete = function (result, mode) {
    if (config.es6) {
      complete(null, result);
    } else {

      callback(null, "/** autogenerated code**/\n" + babelify(result, mode));
    }
  };

  var ast = converter.parseAst(source);

  if (isStyledChosen(config)) {
    toStyled(ast, complete);
  } else {
    throw new Error('css-to-js-webpack-plugin: unknown compilation target');
  }
};